ontoportal-lirmm/bioportal_web_ui

- app/components/switch_input_component.rb
- app/components/switch_input_component/switch_input_component.html.haml
- app/controllers/concerns/submission_updater.rb
- app/controllers/ontologies_metadata_curator_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/submissions_helper.rb
- app/helpers/turbo_helper.rb
- app/views/ontologies_metadata_curator/_attribute_inline.html.haml
- app/views/ontologies_metadata_curator/_attribute_inline_editable.html.haml
- app/views/ontologies_metadata_curator/_form_edit.html.haml
- app/views/ontologies_metadata_curator/_metadata_tab.html.haml
- app/views/ontologies_metadata_curator/_result.html.haml
- app/views/submissions/_form.html.haml
- app/views/submissions/_form_content.html.haml
- config/routes.rb
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/87
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/136
- Add metadata curator admin section 
- Add inline editing 
- Update bulk metadata editing
- Add switch input view component 
- Extract SubmissionUpdater concerns to save and update a submission
> Feature: Metadata curator v2

- app/views/ontologies/sections/_widgets.html.haml
- public/javascripts/widgets/form_complete.js
- public/javascripts/widgets/quick_jump.js
- public/widgets/visualization/index.html
* Update the js code of form_complete and quick_jump
* Fix the visualization widget by setting the rest_domain
> Fix: widgets JS

- app/controllers/application_controller.rb
Fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/134
> Fix: response_errors to use response body

- app/controllers/admin_controller.rb
Fix https://github.com/agroportal/project-management/issues/351
> Fix: Admin ontology process success message 

- app/helpers/ontologies_helper.rb
- app/views/ontologies/sections/_metadata.html.haml
> Fix: Trigger browser reload on summary page links clicks 

- app/views/layouts/_header.html.erb
- app/views/layouts/angular.html.erb
- app/views/layouts/appliance.html.haml
- app/views/layouts/application.html.erb
- app/views/layouts/minimal.html.erb
- app/views/layouts/popup.html.erb
- app/views/notifier/feedback.html.erb
- app/views/ontologies/_submissions.html.haml
- app/views/shared/_ontology_picker_advanced.html.erb
Fix #171, by disabling the cached version and forcing us to reload the page when we come back. This is a temporary fix until we do the full migration of the UI to the new JS code.
> Fix: some bugs on browser back click

- app/views/fair_score/_details.html.haml
- app/views/ontologies/_fairs_score.html.haml
- Use everywhere the same module to show a popup (see  https://github.com/ncbo/bioportal_web_ui/pull/225)
- Remove code duplication
- Remove the usage of the dependency Jquery Facebox
> Feature: Migrate the fair score details popup from Jquery Facebox to Turbo modal

- app/components/switch_input_component.rb
- app/components/switch_input_component/switch_input_component.html.haml
- app/helpers/submissions_helper.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/169
> Fix: Switch component to have a boolean version for submissions form

- app/helpers/submissions_helper.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/170
> Fix: input attribute of type uri getting only the first letter (e.g h) and saving local:h

- Gemfile.lock
- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/landscape_controller.rb
- app/helpers/ontologies_helper.rb
fix https://github.com/agroportal/project-management/issues/120
> Fix: included in data catalog not showing the right name in the button

- app/views/ontologies/sections/_metadata.html.haml
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/71
> Feature: show ontology pull url in summary page if ontology admin

- app/helpers/submissions_helper.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/179
> Fix: Remove the option None for all the submission from select attribute

- .gitignore
- Gemfile.lock
- config/newrelic.yml
Follow up of https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/153
So this can work we need to add the following credentials 
```
new-relic:
license_key:
app_name:  
```
Full documentation can be found here https://doc.jonquetlab.lirmm.fr/share/7b001805-78cd-4deb-894d-335eff6ef9f4
- Fix some typos 
- Remove unused stages
> Feature: Add Newrelic configuration file 

- .gitignore
- Gemfile
- config/newrelic.yml
> Feature: add newrelic production

- app/javascript/controllers/metadata_downloader_controller.js
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/227
> Fix: downloading an empty json metadata file 

- app/views/concepts/_list.html.haml
See https: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/267
fix problem in alphabetical sorting in the display of collection
> Fix: Alphabetical sorting in the the collection members display 

- app/views/home/index.html.haml
Context
See
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/264
Changes
fix bug : links of slices
> Fix:  Erroneous slices links in home page

- app/assets/stylesheets/footer.scss
- app/assets/stylesheets/home.scss
- app/assets/stylesheets/nav_bar.scss
- app/views/home/index.html.haml
- app/views/layouts/_topnav.html.haml
This pull request resolves various responsiveness issues related to the:
- Home page.
- Navigation bar.
- Footer.
> Bug: Fix responsiveness issues

- app/assets/stylesheets/components/regular_button.scss
- app/assets/stylesheets/ontologies.scss
- app/assets/stylesheets/ontology_viewer.scss
- app/assets/stylesheets/summary.scss.erb
- app/components/external_link_text_component.rb
- app/components/internal_link_text_component.rb
- app/components/language_field_component.rb
- app/components/language_field_component/language_field_component.html.haml
- app/components/link_field_component.rb
- app/components/link_field_component/link_field_component.html.haml
- app/components/ontology_subscribe_button_component/ontology_subscribe_button_component_controller.js
- app/components/popup_link_text_component.rb
- app/components/tree_infinite_scroll_component/tree_infinite_scroll_component.html.haml
- app/controllers/application_controller.rb
- app/controllers/ontologies_controller.rb
- app/helpers/application_helper.rb
- app/helpers/concepts_helper.rb
- app/helpers/inputs_helper.rb
- app/helpers/mappings_helper.rb
- app/views/concepts/_details.html.haml
- app/views/concepts/_show.html.haml
- app/views/errors/internal_server_error.html.haml
- app/views/errors/not_found.html.haml
- app/views/layouts/_ontology_viewer.html.haml
- app/views/ontologies/sections/_metadata.html.haml
- app/views/ontologies/sections/_widgets.html.haml
- app/views/ontologies/sections/visualize.html.haml
* update language field component to have a better display of not valid ISO links (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/371/commits/71b96c392573f46bad73337a0a969f6d25ec9bef) 
* fix the error page image not displaying the good color (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/371/commits/dff2500dbcc833e81c0630a7a61a454729622664) 
* fix turbo frame error text extraction from the new errors pages (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/371/commits/f12637e3e1a2f33ecd284d6dcfb40b26c448d016)
* fix summary links section display to use link component (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/371/commits/fc906c7f614897e341ea0be3ec016ee2ec653be7)
* catch remaining cases when concept is nil in the ontology viewer …
> Fix: the new summary page bugs

- app/controllers/landscape_controller.rb
- app/helpers/application_helper.rb
- app/views/landscape/index.html.haml
- app/views/shared/_ontology_picker.html.erb
* Update the landscape page to work with the backend model (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/5624ac6ce99a21dcc97ae0e09d460b157c81d62f)
* Optimize the landscape loading page speed by removing duplicate calls (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/31b3ab9470aef36af636f0e989cad0f9768d25fc)
> Fix: Optimize landscape pages load speed and integration with the new model 

- app/assets/javascripts/bp_admin.js
- app/controllers/admin_controller.rb
- config/routes.rb
See: https://github.com/agroportal/project-management/issues/272
> Feature: add synchronize groups to slices button in admin page

- app/components/display/search_result_component.rb
- app/components/display/search_result_component/search_result_component.html.haml
- app/controllers/search_controller.rb
- app/views/search/index.html.haml
- config/locales/de.yml
- config/locales/en.yml
- config/locales/fr.yml
- config/locales/it.yml
In this PR I fixed the following issues:
- Search page query bug (when we perform a search from the home page)
- Fix search page filters issues 
- Search reuses decendences reveal issues (when we try to open decendences of reuses all the buttons open the same block)
- make search page multilang (put texts on local lang files)
> Fix: Search page issues

- Gemfile
- Gemfile.lock
- app/controllers/login_controller.rb
- app/controllers/users_controller.rb
- config/bioportal_config_env.rb.sample
- config/initializers/bugsnag.rb
* fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/439
* add bugsnag configuration to production (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/464/commits/9013b3fe89fc01ca479c140622f920b0b3d5dc36)
> fix: escape user id and include all attribute when fetched in the user paths

- Gemfile.lock
- app/javascript/controllers/skos_collection_colors_controller.js
fix https://github.com/agroportal/project-management/issues/472
> fix SKOS collections colors not removing all the dots

- app/controllers/agents_controller.rb
- app/helpers/application_helper.rb
- app/helpers/ontologies_helper.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/456 and https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/438
> Fix: ontology description icons link to add APIKEY and fix admin agent edition showing 0 usages after saving  

- app/controllers/properties_controller.rb
- app/helpers/application_helper.rb
- app/helpers/ontologies_helper.rb
- app/views/properties/_properties_tree.html.haml
- app/views/properties/_show.html.haml
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/453
> Feature: enable multilingual to the properties tab

- app/controllers/users_controller.rb
- app/views/users/index.html.haml
- test/fixtures/users.yml
- test/integration/login_flows_test.rb
- test/system/login_flows_test.rb
* Extract find_user method the user controller with correct id escaping (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/872155bb395649351ba5f5a5f759b305616c0bfb)
* Add user reset password test (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/cd40c965dd7c8a1c5be549c2b0bfaf850a53f7c4)
> Fix: user with space reset password 

- app/components/url_resolvability_component.rb
- app/controllers/admin_controller.rb
- app/controllers/check_resolvability_controller.rb
- app/helpers/check_resolvability_helper.rb
- app/views/ontologies/sections/_widgets.html.haml
- app/views/ontologies/sections/metadata/_metrics_evolution_graph.html.haml
* Add a link to see the result details of the URL resolvability check (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/0296f77c1b12a9e95b344b974915ed4191a69d43)
* Fix visualization widget not showing code section (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/e11e0182f3fb586cf326735ebbab3eeb344b8a15)
* Fix the metrics graph evolution not showing use chart component](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/b4965e93c00c84d140a9bd9a1de49ba126b1f362)
* #468 
* #464
> Fix: Release 2.7.4 hotfixes

- app/components/ontology_browse_card_component/ontology_browse_card_component.html.haml
- app/components/summary_section_component/summary_section_component.html.haml
- app/controllers/concerns/submission_filter.rb
- app/controllers/ontologies_controller.rb
- app/helpers/ontologies_helper.rb
- app/helpers/schemes_helper.rb
- app/views/admin/categories/index.html.haml
- app/views/admin/groups/index.html.haml
- app/views/notes/_notes.html.haml
- app/views/ontologies/browser/browse.html.haml
- app/views/ontologies/sections/metadata/_ontology_metrics_section.html.haml
- app/views/submissions/_submissions.html.haml
- bin/run_api
- config/locales/en.yml
- config/locales/fr.yml
Related to https://github.com/agroportal/project-management/issues/309
* internationalization of ontologies helpers
*  Internationalization of remaining files
* update of en.yml file (remove the duplacted keys)
* update of fr.yml file
* fix the bug of missing translate
> Fix: internationalization of french part

- app/assets/stylesheets/home.scss
- app/helpers/check_resolvability_helper.rb
- Resolve a merge conflict found in the check resovablity helper.
- Fix an issue in the style of ontoportal instances home section.
**issue**
**After**
> Fix: Ontoportal instances home section style issue

- app/assets/stylesheets/search.scss
- app/controllers/annotator_controller.rb
- app/controllers/application_controller.rb
- app/controllers/search_controller.rb
- app/helpers/application_helper.rb
- app/views/search/index.html.haml
- app/views/statistics/index.html.haml
- config/locales/en.yml
- config/locales/fr.yml
* https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/561
* https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/562
> Merge to master: Release 2.7.4.1  - Fix annotator fast context & add search json icon 

- app/assets/stylesheets/application.css.scss.erb
- app/assets/stylesheets/content_finder.scss
- app/controllers/content_finder_controller.rb
- app/helpers/application_helper.rb
- app/javascript/controllers/content_finder_controller.js
- app/javascript/controllers/index.js
- app/views/content_finder/index.html.haml
- Adding content finder page to be able to request a resource from a graph and diplay it with different format
- Supported formats:
- JSON.
- XML.
- NTRIPLES
- TURTLE
[demo_content_finder.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/66650181/eac9ee10-95c1-46f9-aa56-d7dbe7cc8223)
> Feature: Adding Content Finder Page

- app/controllers/concerns/ontology_updater.rb
- app/controllers/ontologies_controller.rb
- app/helpers/ontologies_helper.rb
- config/locales/en.yml
- config/locales/fr.yml
* fix https://github.com/agroportal/project-management/issues/488 
* fix summary not ready alert message to not hide the data sections if any submissions is ready (latest or previous)
> Fix: submission date and summary not ready

- app/assets/stylesheets/register.scss
- app/controllers/users_controller.rb
- app/views/users/_form.html.haml
- app/views/users/new.html.haml
- config/bioportal_config_env.rb.sample
- config/locales/en.yml
- config/locales/fr.yml
- test/integration/login_flows_test.rb
- test/system/login_flows_test.rb
- Add terms and conditions check box in register page, and make it required
- Add terms and conditions links to the footer
> Feature: Add terms and conditions

- app/controllers/instances_controller.rb
- app/helpers/components_helper.rb
- app/helpers/inputs_helper.rb
- app/helpers/search_helper.rb
- app/views/instances/_details.html.haml
* fix the paginated list selected value to not select on each new page (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/581/commits/fd971a90b3758fdfc56c336943857e127bf56fb1)
* fix instance search type filter to not include everything (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/581/commits/74737dcf92366efc5811cc09dc7f6125a7e13f4f)
> Fix: new instance search feature to filter strictly only NamedIndividual 

- app/controllers/concerns/search_aggregator.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/578
> Fix: Search page results broken links

- config/routes.rb
Related issue:
https://github.com/agroportal/project-management/issues/481
> Fix: delete submission

- app/controllers/application_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/subscriptions_controller.rb
- config/locales/en.yml
- config/locales/fr.yml
fix https://github.com/agroportal/project-management/issues/531
origin https://github.com/ncbo/bioportal_web_ui/issues/308
> Fix: Note thread show action

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/recommender/index.html.haml
- config/bioportal_config_test.rb
- test/fixtures/recommender.yml
- test/system/agent_flows_test.rb
- test/system/login_flows_test.rb
- test/system/recommender_page_test.rb
- test/system/submission_flows_test.rb
- test/test_helper.rb
In this pull request, I've incorporated end-to-end (E2E) system tests for the recommender page across various use cases and scenarios.
Technically, I've opted not to rely on the current production API for fetching data. Instead, I've implemented mock responses for all API calls specific to this page. This ensures that our tests solely focus on the UI, and they remain effective even if we modify elements in the database or make other changes.
[Capture vidéo du 26-04-2024 11:47:46.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/2292cea2-4665-4fa6-94bb-90fb977dd520)
> Feature: Add recommender tests

- app/controllers/concerns/submission_filter.rb
- app/helpers/fair_score_helper.rb
* Implement caching for the ofaire service (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/68697c781531f782cf7eff133010c09e674e250e)
* Fix the browse page popularity sort (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/f29ba975b026764ecc2e31d300859d0dc97bad60)
> Fix: Browse page ofaire cache and popularity sort

- app/controllers/home_controller.rb
Issue number 7 here: https://github.com/agroportal/project-management/issues/546
> Fix: Home annotator redirection to annotator page with non populated input

- app/assets/stylesheets/ontologies.scss
- app/components/display/rdf_highlighter_component/rdf_highlighter_component_controller.js
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/544
Demo:
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/606c6276-c570-4710-a40a-097289d3739d
> Fix: Download button in summary export metadata

- app/views/layouts/ontology_viewer/_header.html.haml
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/602
> Feature: Make view of clickable in summary page header

- app/controllers/admin/categories_controller.rb
- app/controllers/admin/groups_controller.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/637
Screenshots:
> Feature: use the ontologies selector by name and acronym in edit groups and categories (Admin page)

- app/components/input/text_area_component.rb
- app/components/input/text_area_component/text_area_component.html.haml
- app/helpers/inputs_helper.rb
- app/helpers/submission_inputs_helper.rb
Related issue: 
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/523
> Feature: Make text area resisable in upload ontology and edit submission forms

- app/assets/stylesheets/agents.scss
- app/helpers/agent_helper.rb
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/636
> Fix: The issue when the agent has no acronym

- app/javascript/controllers/label_ajax_controller.js
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/528
The problem was traced back to an issue in the Stimulus base project, as detailed in [stimulus issue #618](https://github.com/hotwired/stimulus/issues/618)
and the only proposed solution is by set a timout of 0s in the connect method, and it worked.
> Fix: Wrong concepts chips links

- app/views/home/feedback/feedback.html.haml
- config/bioportal_config_env.rb.sample
- config/locales/en.yml
- config/locales/fr.yml
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/660
Screenshots:
> Feature: Add issues and requests link to the footer and feedback form

- app/assets/stylesheets/ontologies.scss
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/661
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/4c34c823-69fc-4c15-b19b-7f46f2ef8ef3
> Fix: the width of the ontlogy viewer left block of classes, instances, ... 

- app/helpers/submission_inputs_helper.rb
- app/helpers/submissions_helper.rb
- lib/tasks/schema.rake
fix  https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/200 and https://github.com/agroportal/project-management/issues/484
* Show submission attributes label instead of the keys in the selector (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/eeaf81b6a16531cd135ed07f91d21ae73827cc58)
* Add ontologies properties to the submission properties selector (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/90a13bfded105cf02764f734876a75bc0d494190)
> Fix: submissions properties selector labels and include ontologies properties

- app/components/display/rdf_highlighter_component/rdf_highlighter_component_controller.js
Fix first issue in https://github.com/agroportal/project-management/issues/578
> Fix: Json file extention in export metadata summary page

- app/components/table_component.rb
- app/components/table_component/table_component.html.haml
- app/components/table_component/table_component_controller.js
- app/views/mappings/_count.html.haml
fix https://github.com/lifewatch-eric/ecoportal_web_ui/issues/54
> Feature: add search placeholder to data table component

- app/helpers/mappings_helper.rb
- app/views/mappings/_show_line.html.haml
fix https://github.com/lifewatch-eric/ecoportal_web_ui/issues/55
> Fix: mappings concept link opening empty pages

- docker-compose.yml
I got this error when I tried to run tests locally
I moved the links to the db and cache from the Xapp to dev and prod
> Fix: docker compose to make tests work

- app/controllers/ontologies_redirection_controller.rb
Adding rewrite condition before the rewrite rule to ensure that we redirect the correct ontology URIs
> Feature: rewrite condition in redirection rules

- app/views/agents/_agent.html.haml
- app/views/agents/index.html.haml
- config/locales/en.yml
- config/locales/fr.yml
Related issue
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/591
screenshot
> Feature: add acronym column in the agents table in the admin page

- app/components/url_resolvability_component.rb
- app/helpers/check_resolvability_helper.rb
- app/views/check_resolvability/index.html.haml
- Calculate response time of each of the format request
- Calculate the average response time for all the requests made
- add new format equivalents
> Feature: add response time calculation in check resolvability tool

- app/helpers/submission_inputs_helper.rb
- docker-compose.yml
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/714
**Screenshots**
> Fix: Lost view of value on submssion creation or editition

- app/controllers/ontologies_controller.rb
Fix https://github.com/agroportal/project-management/issues/528, now we can see the ontology view of value in the relation networks
> Feature: add ontology viewOf the the summary page relation network

- app/controllers/agents_controller.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/592
> Fix: Remove agent usages

- config/locales/en.yml
- config/locales/fr.yml
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/707
> Fix: Saving and Cancel button locals text capitalization

- app/controllers/agents_controller.rb
Related back PR:
https://github.com/ontoportal-lirmm/ontologies_api/pull/90
> Fix: pass qf param in agents search

- app/helpers/agent_helper.rb
- app/views/agents/_form.html.haml
- bin/run_api
- test/application_system_test_case.rb
- test/fixtures/agents.yml
- test/fixtures/ontologies.yml
- test/system/agent_flows_test.rb
- test/system/submission_flows_test.rb
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/589
> Fix: Hide affiliations when agent is organization in agent form

- app/helpers/agent_helper.rb
Fix issues 14, 15 and 16 here: https://github.com/agroportal/project-management/issues/598
https://github.com/user-attachments/assets/7e2aecd1-02ff-43e8-935c-6b64c13746c1
> Fix: Enhance agent chip component

- app/components/ontology_browse_card_component/ontology_browse_card_component.html.haml
- app/controllers/concerns/search_aggregator.rb
- app/controllers/concerns/submission_filter.rb
- app/helpers/fair_score_helper.rb
- app/helpers/ontologies_helper.rb
- app/views/ontologies/browser/_ontologies.html.haml
- app/views/properties/_show.html.haml
- Fix the browse page showing an error if the second page (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/ba306bd138ea6fbb3b9d98415fe5aa402661a6d7) (resolve https://github.com/agroportal/project-management/issues/600)
- Handle the case of errors in indexing the ontology name or acronym (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/6735b717394477eddff99c69608842671993563f)
- Remove parents from the properties show partial (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/9e3841e6a78dc0b1d1d41ea375e20db6c6968661) (related to  https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/742 )
- Don't cache the fair score call response if empty or status error (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/4f09782e9000efc37d0566df813a2edafb25 …
> Fix: Release 2.9.2 hotfixes

- app/controllers/users_controller.rb
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/764
> Fix: User Account Page, Infinite redirect loop to login page

- app/javascript/controllers/simple_tree_controller.js
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/776
> Fix: Summary page scroll up auto multiple times

- app/helpers/application_helper.rb
- app/views/ontologies/ontologies_selector/ontologies_selector_results.html.haml
Related issues:
https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/784 (last comment)
https://github.com/agroportal/project-management/issues/619#issuecomment-2444092054
**Screenshots**
-----
> Fix: ontologies selector localization text and add "[view]" of the views in the list

- Gemfile.lock
- app/components/tree_link_component.rb
- app/helpers/multi_languages_helper.rb
- test/helpers/application_test_helpers.rb
- test/system/login_flows_test.rb
- test/system/submission_flows_test.rb
This fixes PR resolve https://github.com/agroportal/project-management/issues/515#issuecomment-2444655766, by selecting any language found over the not tagged ("@none") label in the all languages mode.
> Fix: update select_language_label  helper to select f no english found any language remaining over the not tagged

- app/assets/stylesheets/ontologies.scss
- app/controllers/application_controller.rb
- app/controllers/language_controller.rb
- app/helpers/components_helper.rb
- app/helpers/multi_languages_helper.rb
fix https://github.com/biodivportal/ontoportal_web_ui/issues/9 and https://github.com/biodivportal/ontoportal_web_ui/issues/10
> Fix: selecting a disabled language (e.g germany) as a local language 

- app/controllers/home_controller.rb
- app/helpers/home_helper.rb
> Fix: tests after merging home page bubbles if no analytics enabled

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- config/routes.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/856
> Fix: users edition and login_as  with the `@` symbol in there usernames

- app/helpers/instances_helper.rb
https://github.com/user-attachments/assets/50095b18-6832-43e0-a12e-443db6458d41
> Feature: Add `propertyid` in the URL parameters of `Instances` subtab for enhanced navigation

- app/helpers/home_helper.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/849
> Fix: Self portal tooltip not working in the home page

- app/assets/stylesheets/concepts.scss
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/874
Screenshot:
> Fix: Concept raw data chips overflow

- .github/workflows/docker-image.yml
- Dockerfile
- Gemfile.lock
Changed files
- `Dockerfile`
- `docker-image.yml`
- update Gemfile.lock
> Feature: build docker UI image for ruby 3.1

- .env.sample
- .github/workflows/brakeman-analysis.yml
- .github/workflows/docker-image.yml
- .github/workflows/tests-real-data-stageportal.yml
- .github/workflows/tests-system.yml
- .github/workflows/tests.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- app/components/display/search_result_component.rb
- app/controllers/application_controller.rb
- app/controllers/ontologies_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/application_helper.rb
- app/helpers/internationalisation_helper.rb
- app/helpers/multi_languages_helper.rb
- app/helpers/ontologies_helper.rb
- app/helpers/turbo_helper.rb
- app/views/search/index.html.haml
- config/bioportal_config_env.rb.sample
- config/locales/en.yml
- config/locales/fr.yml
- docker-compose.yml
- package.json
- test/application_system_test_case.rb
- test/controllers/ontologies_controller_test.rb
- test/fixtures/submissions.yml
- test/integration/login_flows_test.rb
- test/system/agent_flows_test.rb
- test/system/login_flows_test.rb
* https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/940
* https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/943
* https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/930
> Merge to master: Release 3.1.0 -  Support Ruby 3.2

- app/controllers/agents_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/concepts_controller.rb
- app/controllers/concerns/uri_redirection.rb
- app/controllers/login_controller.rb
- app/controllers/mappings_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/ontologies_controller.rb
- app/controllers/ontologies_redirection_controller.rb
- app/controllers/search_controller.rb
- app/helpers/agent_helper.rb
- app/helpers/ontologies_helper.rb
Fixed issues:
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1138
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1133
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1132
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1130
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1129
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1110
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1099: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/1147/commits/7393df9adbf5f4fdbeeefcbed521f0fe8b86dec4
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1098: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/1147/commits/c3d63146f3cb80ac4bc9c95c0c63795abe42f3cf
- …
> Fix: sentry issues iteration 1

- app/controllers/concerns/submission_filter.rb
- app/controllers/concerns/uri_redirection.rb
- app/controllers/ontologies_redirection_controller.rb
- app/javascript/controllers/browse_filters_controller.js
- Fix for: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1012
- Fix retired filter to show only retired ontologies
- Fix some missing variables reported in sentry
> Fix: Error when filters and federation are active
