ontoportal-lirmm/bioportal_web_ui

- app/components/concept_details_component.rb
- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/ontologies_metadata_curator_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/schemes_helper.rb
- app/helpers/turbo_helper.rb
- app/javascript/application_esbuild.js
- app/javascript/controllers/turbo_frame_error_controller.js
- app/views/ontologies/_submissions.html.haml
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/87
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/136
- https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/138
- Add edit and delete buttons to the ontology submission table 
- Show success/error alerts after delete and remove the line in the table
- Fix  some bugs of showing schemes with no ids 
- Fix error response handling 
- Add and remove turbo stream helper 
- Use as a default Turbo confirm method Alertify
- Fix turbo frame error handling
> Feature: Add edit and  delete submissions for users

- app/assets/javascripts/bp_notes.js
- app/components/ontology_subscribe_button_component.rb
- app/components/ontology_subscribe_button_component/ontology_subscribe_button_component.html.haml
- app/components/ontology_subscribe_button_component/ontology_subscribe_button_component_controller.js
- app/helpers/application_helper.rb
- app/helpers/notes_helper.rb
- app/javascript/component_controllers/index.js
- app/javascript/controllers/application.js
- app/javascript/controllers/index.js
- app/views/notes/_list.html.haml
- app/views/notes/_ontology_list.html.haml
- app/views/users/show.html.haml
- Migrate the old js code to the Stimulus controller
- Create a reusable component to subscribe a user to an ontology  
- Remove duplicate code
- Fix a bug that subscribes the user to the same ontology multiple times 
- Fix a bug that makes the user that wanted to unsubscribe to an Ontology instead unsubscribe him to all his subscriptions
> Feature: Create subscribe to ontology button component 

- app/views/login/lost_password_success.html.haml
Before, to make a message card component without a title, you need to fill the parameter title with "no-title"
Now, to do the same thing, you just need to keep the parameter title empty (by default it's nil).
In the lost password success we used the old message card component.
I removed the parameter title.
> Fix: Password recovery success message

- Gemfile
- app/components/card_message_component.rb
- app/components/card_message_component/card_message_component.html.haml
- app/views/layouts/component_preview.html.erb
- config/application.rb
- config/routes.rb
- test/components/previews/card_message_component_preview.rb
- test/components/previews/chips_component_preview.rb
**Disadvantages of not having a lookbook:**
- Limited understanding: Developers may have a limited understanding of how each component can be used or may miss potential use cases for the library.
- Time-consuming: Developers may need to spend more time researching and testing each component individually, which can be time-consuming and may lead to inefficiencies.
I made a lookbook which is a visual representation of a library of pre-built components that showcases the design, functionality, and use cases of each component. It is a tool that helps developers and other stakeholders to understand how the library works and how it can be used to build new features and functionality.
It provides the possibility of editing the components and getting a ready-made code 👌
> Feature: Lookbook

- app/views/users/show.html.haml
This pull request addresses an issue on the account page where the names of submitted ontologies are too long and negatively impacting the design of the page. 
To improve the user experience, this pull request proposes using acronyms for the ontology names instead. The acronyms are shorter and easier to read, while still allowing users to easily recognize their ontologies.
- Updated the account page to use ontology acronyms instead of full names in the section displaying submitted ontologies.
- Tested the changes to ensure they do not negatively impact the functionality of the account page or other related features.
> Feature: Update account page submitted ontologies

- Gemfile.lock
- app/assets/stylesheets/components/chip_button.scss
- app/assets/stylesheets/components/index.scss
- app/assets/stylesheets/theme-variables.scss.erb
- app/components/chip_button_component.rb
- app/components/chip_button_component/chip_button_component.html.haml
- test/components/previews/chip_button_component_preview.rb
- Add chip button component to lookbook
- Add light color variable to theme variables (we need it in this new component)
> Feature: Add chip button component to lookbook

- app/assets/stylesheets/nav_bar.scss
Follow up of https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/238, to fix a conflict with a global bootstrap class (`nav-link`)
> Fix: replace nav_bar  css nav-link to top-nav-nav-link to prevent conflicts

- app/helpers/ontologies_helper.rb
Context
See https://github.com/agroportal/project-management/issues/425
https://github.com/agroportal/project-management/issues/425#issuecomment-1605732360
Changes
restyle text display when it is uri to a button
> Fix: ontology style text display when it is  uri

- app/components/alert_message_component.rb
- app/components/alert_message_component/alert_message_component.html.haml
see : https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/266
- fix bug of display text in alert
> Fix: bug alert text when there is no collection view of ontology

- app/assets/stylesheets/nav_bar.scss
- app/components/ontology_search_input_component.rb
- app/components/ontology_search_input_component/ontology_search_input_component.html.haml
- app/components/search_input_component.rb
- app/components/search_input_component/search_input_component.html.haml
- app/components/search_input_component/search_input_component_controller.js
- app/javascript/component_controllers/index.js
- app/views/home/index.html.haml
- app/views/layouts/_topnav.html.haml
After merging these two https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/238 and https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/235 I wanted to extract the new input to search an ontology by name/acronym in a component because I will need it  in another parallel work (this one https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/278)
So this PR extracted and updated the code to make it generic and work everywhere with ontologies or any other searchable object (persons, ...)
- Add search input component (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/e57cbc37e3db4feb2d4e80ae52c9381da4320428) 
- Add ontology search input component re-using search-input component (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/08bcb0383686e8f68fa459fbe2ada5cd …
> Feature: Extract search input component

- app/controllers/application_controller.rb
- app/controllers/ontologies_controller.rb
- app/views/ontologies/concepts_browsers/_concepts_tree.html.haml
Resolve https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/298
- show error message if alert component if there is no roots 
- the list tab selected if there are collections
- the dates tabs selected if there are no empty
> Fix: Bug missing roots display

- app/controllers/admin/categories_controller.rb
- app/controllers/admin/groups_controller.rb
- app/controllers/concerns/submission_updater.rb
Context
See https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/332
Changes
- Fix the bug in edit group and category
> Fix: generated bug after edit group and category 

- .github/workflows/tests.yml
- Gemfile.lock
- app/components/language_field_component.rb
- app/components/language_field_component/language_field_component.html.haml
- app/helpers/application_helper.rb
- config/bioportal_config_test.rb
- config/database.yml.sample
- config/environments/test.rb
- test/controllers/application_controller_test.rb
- test/controllers/landscape_controller_test.rb
- test/controllers/ontologies_controller_test.rb
* add GitHub CI tests (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/377/commits/69b2a21a0687842e17aac4ecf9293a4db8b7e603)
* Add the following tests (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/377/commits/4f38aff7598efb6555deaaeeff67e4c28177f147):
*  Check that these pages: home, projects, annotator, recommender, mappings ontologies, and feedback, are accessible.
* Take a sample of 5 ontologies,  and check for each of their pages: summary, classes, notes, widgets, instances, schemes, collection, and properties; they are accessible.
> Feature: Add UI tests infrastructure and Github action 

- .github/workflows/deploy.yml
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/deploy/test.rb
This update the deploy action https://github.com/ncbo/bioportal_web_ui/pull/222), to work in our context. By making more configurable 
- Add test environment option (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/0ca14b77ed331dc77f3b394b9e31effe6f4bbcf0 and https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/60b0a6873a64b59894da23094aa2934674eb4078)
- Use a variable for the `config folder path` to use in the `get_config` task (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/fdd665eab63201a13378fef9035751149e09618a)
- Set the deployment rails_env to "appliance" for all the environments (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/05f4b121e9ad611036fb53c7d05bf20e12bb5d9d)
- Make the jump box `host` and `username` configurable for the …
> Feature: Implement CI deployment  for development servers 

- app/controllers/application_controller.rb
- app/mailers/notifier.rb
- app/views/notifier/error.html.haml
See: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/362
https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/385
> Fix: add current url in portals errors

- Gemfile.lock
- app/components/ontology_subscribe_button_component.rb
- app/components/ontology_subscribe_button_component/ontology_subscribe_button_component.html.haml
- app/controllers/agents_controller.rb
- app/controllers/concerns/ontology_updater.rb
- app/controllers/concerns/submission_updater.rb
- app/controllers/ontologies_controller.rb
- app/controllers/ontologies_metadata_curator_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/application_helper.rb
- app/helpers/fair_score_helper.rb
- app/helpers/ontologies_helper.rb
- app/javascript/controllers/ontology_viewer_tabs_controller.js
- app/views/layouts/_ontology_viewer.html.haml
- app/views/ontologies_metadata_curator/_attribute_inline.html.haml
- app/views/ontologies_metadata_curator/_attribute_inline_editable.html.haml
- app/views/ontologies_metadata_curator/_metadata_table_row.html.haml
- app/views/submissions/_submissions.html.haml
- app/views/submissions/edit.html.haml
- bin/ontoportal
- config/routes.rb
- test/system/submission_flows_test.rb
* https://github.com/ontoportal-lirmm/ontologies_api_ruby_client/pull/14 
* Optimize the summary page loading time ( 51.06% less time), by 
* [update the summary watch button to be lazy loaded](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/411/commits/0b65c2497d6e251e8aa6f1682d3a191a542883c6)
* [optimize the submissions partial to not load the latest submission twice](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/411/commits/58f7faceeccb48f4d714738a619464a38c4b1c11)
* Optimize submission update page loading time  (79.99% less time), by 
* [optimize the submission update page speed](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/411/commits/3e875371837a8900623e8b5840dbe9602d09bed7)
* Optimize metadata curator page loading time (97.1% less time), by 
* …
> Fix: Optimize some pages load speed (metadata curator, summary, agents admin)

- app/assets/stylesheets/components/index.scss
- app/assets/stylesheets/components/range_slider.scss
- app/assets/stylesheets/recommender.scss
- app/components/input/range_slider_component.rb
- app/components/input/range_slider_component/range_slider_component.html.haml
- app/components/input/range_slider_component/range_slider_component_controller.js
- app/controllers/recommender_controller.rb
- app/javascript/component_controllers/index.js
- app/javascript/controllers/recommender_controller.js
- app/views/recommender/index.html.haml
> Fix: Add slider component to recommender page 

- app/views/recommender/index.html.haml
Done in this PR:
- Add keywords tooltip.
- Change annotator button text from 'Get results from annotator' to 'Call Annotator with the same input'.
> Feature: Add keywords tooltip in Recommender page

- app/helpers/submission_inputs_helper.rb
Fixed an issue in the ontology_view_of_input function where a missing closure resulted in the disappearance of ontology view of from the upload ontology form.
> Fix: Ontology views in upload ontology 

- app/components/layout/reveal_component.rb
- app/controllers/ontologies_controller.rb
- app/helpers/submission_inputs_helper.rb
Auto fill ontology view of input when we click the '+' button in summary page, see the demo for a better understanding.
[Capture vidéo du 22-02-2024 17:59:02.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/aebf6766-16a8-4012-bccd-bf82bee167c1)
> Fix: Auto fill ontology viw of input when we click the '+' button in summary page

- app/components/field_container_component.rb
- app/components/layout/horizontal_list_component.rb
- app/components/link_field_component/link_field_component.html.haml
- app/helpers/application_helper.rb
- app/helpers/components_helper.rb
- app/helpers/ontologies_helper.rb
- app/views/ontologies/sections/_metadata.html.haml
See: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/485
> Fix: display of content sections in summary page by adding option to disable text truncate 

- app/assets/stylesheets/home.scss
- app/views/home/index.html.haml
I took on the perspective of a regular user. Upon landing on the home page, the ontology bubbles immediately caught my attention.
AGROVOC is the most visited ontology showed in the biggest bubble, I wanted to see more details about it so I clicked on it, but I found that it's not clickable.
So I had to manually copy the name of it and initiate a separate search.
- I made the home page bubbles clickable.
[Capture vidéo du 23-02-2024 12:13:18.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/2f772632-e738-4489-b364-5f4ec0d7d1a8)
> Feature: make home bubbles clickable

- app/components/select_input_component/select_input_component_controller.js
The current implementation of our select input component presents a limitation when dealing with a large number of options. The component only displays a limited set of choices, necessitating users to start typing the name of a specific option when it's not displayed.
I made the select input component displays all available options, regardless of their quantity.
> Fix: Make select component displays all options

- app/helpers/ontologies_helper.rb
See: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/522
> Fix: Summary shortcut buttons should open to another Windows 

- app/controllers/annotator_controller.rb
- app/controllers/recommender_controller.rb
- app/controllers/search_controller.rb
- app/javascript/controllers/form_url_controller.js
- app/javascript/controllers/index.js
- app/views/annotator/index.html.haml
- app/views/recommender/index.html.haml
- app/views/search/index.html.haml
Current URLs of the search, Annotator and Recommender services, show the lists of params in this way:
But the api url shows:
I made API and UI urls harmonized for the search, recommender and annotator pages.
[Capture vidéo du 12-03-2024 12:42:50.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/4f5ff14f-e9d5-4f11-8480-bf88d6e3f13c)
"%2C" is a URL-encoded representation of the comma "," done by default by the browser to ensure that the special character is transmitted correctly.
> Fix: Harmonize API and UI urls in Search, Annotator and Recommender pages

- app/assets/stylesheets/components/chip_button.scss
- app/assets/stylesheets/ontology_details_header.scss
- app/views/layouts/ontology_viewer/_header.html.haml
- app/views/ontologies/sections/metadata/_ontology_description_section.html.haml
- Distinguish view by adding the view tag beside the name and add the reference ontology in the navigation.
- Fix ontology image position issue 
- Limits heights of different sections and add a see more button if needed (like for categories and subjects)
> Feature: Add view badge to the summary header section 

- app/controllers/annotator_controller.rb
When we use special characters in the annotator's text input like "%", it throws an error.
We encode the input text before doing the api fetch.
> Fix: Allow special characters in annotator's text input

- app/controllers/annotator_controller.rb
- app/views/statistics/index.html.haml
- config/locales/en.yml
- config/locales/fr.yml
- Fix statistics page syntax error.
- Update ontoportal instances home section title (english: Other OntoPortal Instances, french: Autres installations d’OntoPortal).
- Fix fast context option in annotator page (but the input text doesn't accept special chars anymore, when you type a text that contains special chars, then we take off this chars and we do the submit)
> Fix: Annotator fast context special chars issues & statistics page syntax error

- app/assets/stylesheets/search.scss
- app/controllers/annotator_controller.rb
- app/controllers/application_controller.rb
- app/controllers/search_controller.rb
- app/helpers/application_helper.rb
- app/views/search/index.html.haml
[Capture vidéo du 05-04-2024 07:41:43.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/19755781-ed1f-4c56-944a-b15ea51b2404)
> Feature: Add json button to search page

- app/controllers/application_controller.rb
- app/controllers/concerns/submission_filter.rb
- app/controllers/ontologies_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/application_helper.rb
- app/helpers/fair_score_helper.rb
- app/helpers/metadata_helper.rb
- app/helpers/submission_inputs_helper.rb
- app/helpers/submissions_helper.rb
- app/javascript/controllers/browse_filters_controller.js
- app/views/ontologies/browser/_ontologies.html.haml
- app/views/ontologies/browser/browse.html.haml
- app/views/ontologies/ontologies_selector/ontologies_selector_results.html.haml
- app/views/submissions/_form_content.html.haml
See https://github.com/agroportal/project-management/issues/241 and https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/425
* Optimize fetched attributes in the browse page in API mode (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/572/commits/e554b9dcb490a5426f32a8aebeac43b71cfa5a84)
* Paginate the browse page 
* Update ontologies browse to use API or Index (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/572/commits/9c659e5414fd357e61c70faa008673728d74c28d)
* Add cache for the fair_score and submission endpoint (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/572/commits/17888ef535ca9c80f1d37c256ea1f456a50a7766)
* Internationalize a sentence in the browse and ontologies selector views (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/572/c …
> Feature: Improve Browse page  performance

- app/assets/stylesheets/application.css.scss.erb
- app/assets/stylesheets/tools.scss
- app/controllers/home_controller.rb
- app/helpers/components_helper.rb
- app/views/check_resolvability/index.html.haml
- app/views/home/tools.html.haml
- app/views/layouts/tool.html.haml
- app/views/search/index.html.haml
- config/bioportal_config_env.rb.sample
- config/locales/en.yml
- config/locales/fr.yml
- config/routes.rb
This PR adds the tools page, where we will list the possible tools extracted from Ontoportal, as URL checker and content converter, ...
*  Add tools page (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/559/commits/d672a34b941ecafdf8d635fa96faf0ff337f4a54)
* Add tools link to the footer](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/559/commits/6a249644448906134451635b8c11a49034169eaf)
* Extract search input in the search page to re-use in url checker tool (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/559/commits/3eaf35bfec6a78deeaadd4f0e1ed9dbc3718f018)
> Feature: Add OntoPortal tools age

- config/locales/en.yml
- config/locales/fr.yml
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/588
> Fix: Restore the new sample text of the annotator and recommender

- app/controllers/admin_controller.rb
- app/controllers/concerns/search_content.rb
- app/controllers/concerns/submission_filter.rb
- app/helpers/fair_score_helper.rb
* Fix the paginated list selected value to not select on each new page (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/596/commits/fd971a90b3758fdfc56c336943857e127bf56fb1)
* Fix instance search type filter to not include everything (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/596/commits/74737dcf92366efc5811cc09dc7f6125a7e13f4f)
* Fix the auto-selection of `isOfType` filter on browse page (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/596/commits/096e8f5e35accb42d5a41e70453414372b719d54)
* Fix search properties redirection to use `propertyid` not `instanceid` (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/596/commits/4f8ca1a72e79915b178a0e4197c7bafc70c66ad7) (fix https://github.com/agroportal/project-management/issues/521)
* Fix admin …
> Fix: new instance details page, properties selected property display and browse page ontology type filter

- Gemfile
- Gemfile.lock
- config/i18n-tasks.yml
This PR adds the possibility to import or export in CSV, the locale files  
```
bundle exec i18n-tasks csv-export
```
```
bundle exec i18n-tasks csv-import
```
I will import from or export into `tmp/i18n-export/main.csv`
> Feature: add a script to import or export a CSV of the i18n locales

- app/components/card_message_component/card_message_component.html.haml
- app/controllers/login_controller.rb
- app/views/login/lost_password.html.haml
Fix the reset password no more working after the french internationalization of the page 
* Fix user reset password internationalization issue (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/605/commits/f693d291538646f957b1cd98bed9f1abaed8956a)
* Get user info in reset password (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/605/commits/2ce3d5b11e408fc6ea45c62c175ebd949a6b0283)
* Fix card message component image (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/605/commits/7f607e3f668ead0eaf89019787f5788778e7b289)
> Fix: user reset password internationalisation issue

- app/components/clipboard_component/clipboard_component_controller.js
Trim text in the copy button in the clipboard stimulus controller
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/66650181/4fadd337-1a6d-495f-9dcf-e6b5fd072220
> Fix: trim the copied text in the clipboard stimulus controller

- app/components/table_component/table_component_controller.js
- app/helpers/multi_languages_helper.rb
- https://github.com/agroportal/project-management/issues/512
- Fix the issue of the duplicated elements when we change the language
The issue was that when refreshing the portal language using turbo, it didn't remove old initialized stimulus elements (tables, selectors) so it duplicated the initialization, the solution was to disable it, as it does not affect the user experience.
> Fix: Data tables warning issue

- app/helpers/submission_inputs_helper.rb
Related issue: https://github.com/agroportal/project-management/issues/557#event-12970003146
Screenshot:
> Fix: Reject the current ontology from appearing in the ontologies selector in editing the submission's relations

- app/javascript/controllers/simple_tree_controller.js
https://github.com/agroportal/project-management/issues/479
- In the JS we get the active element and then we scroll to keep in in view.
- But the key thing here is to wrap the whole function inside a setTimout of a 0s, why?
- When JavaScript code is executed directly, it runs synchronously as part of the current execution context.
- When JavaScript code is executed inside a setTimeout with a delay of 0 milliseconds, it is scheduled to run asynchronously. The function inside setTimeout is scheduled to run after the current execution context completes, meaning it will be placed in the task queue.
See this example:
```
console.log('Start');
setTimeout(() => {
console.log('Inside setTimeout');
}, 0);
console.log('End');
```
Output:
```
Start
End
Inside setTimeout
```
**Why we need this** …
> Feature: Scroll to the selected term in the tree view

- config/locales/en.yml
- config/locales/fr.yml
fix the word URL to URI in check resolvability in French and English languages
English:
French:
> Fix: change URL to URI in check resolvability

- app/helpers/concepts_helper.rb
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/620
Demo:
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/6f6f7d03-153c-4841-8158-e6a0ee815b1f
> Fix: Multiple highlighted terms in the date view

- app/assets/stylesheets/components/concept_details.scss
- app/assets/stylesheets/concepts.scss
- app/views/concepts/_show.html.haml
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/648
Screenshot:
> Fix: concept details table layout max-with when long strings

- app/controllers/concerns/ontology_updater.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/586
* handle the case reset_agents in edit submissions error state are already Agents (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/ea168c62359aadd8e52a69f5474aa6b38681ce88)
> Fix: handle the case reset_agents in edit submissions error state are already Agents

- .dockerignore
- Dockerfile
- Gemfile
- Gemfile.lock
- bin/ontoportal
- config/environment.rb
- config/initializers/graphql_client.rb
- docker-compose.yml
* Update Dockerfile to precompile assets and create config files (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/666/commits/d59fb84357ed4460d6f226629b1cc5a8f87581a9)
* Disable graphql initializer as not used and raise issues with docker (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/666/commits/813a55409f924a2c7a0448e2249414243ddc5929)
* Docker ignores local credentials files so that will be created when on run (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/666/commits/96a4d05f39ec9f0de788aa1c4f21cb6eb6aa5406)
* Update docker-compose file to have two services for dev and production (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/666/commits/c25f6682794ee32c0f59b3a7466f03b957b56091)
> Feature: update docker compose to have a production service

- app/javascript/controllers/label_ajax_controller.js
Adjust the fix we did in this PR: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/638
The solution used in the previous PR was to add a timeout of 0s but in prod it seems like the JS ignore the timeouts of 0s so I used 1ms instead to make it work.
> Fix: Adjust the fix of concepts details wrong chips URLs

- app/controllers/concerns/ontology_updater.rb
- app/controllers/ontologies_controller.rb
- app/views/ontologies/new.html.haml
- Keep the values of: description, ontology language, status, creation date, contact infos when the user submit a form that contains errors.
- Change the default value of status from alpha to production.
- Change the default value of the creation date from empty to today’s date.
- Fix the issue of getting status field filled with 400 when we submit a wrong form.
- Fix the issue of infinite loading button when we put a wrong URI.
> Fix: Upload ontology form errors, lost filled inputs 

- Gemfile
Move pry gem outside development block in gemfile to fix an issue that prevent deployement.
> Fix: Move pry gem outside development block in gemfile

- Gemfile
- bin/ontoportal
- docker-compose.yml
This fixes is for using the docker-compose file of the bioportal_web_ui in the ontoportal_docker script: 
- add the port 3000 to run the script correctly
- add some commands when running production mode
> Fix: run production mode

- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/views/admin/index.html.haml
- app/views/home/index.html.haml
This PR hides analytics-related features if not enabled, 
* Hide see details buttons on the home page if  analytics are not enabled (fix https://github.com/lifewatch-eric/ecoportal_web_ui/issues/51)
* Hide the analytics admin page if analytics are not enabled
* Use TripleStore to show ontology count metrics on the home page if analytics are not enabled (fix https://github.com/lifewatch-eric/ecoportal_web_ui/issues/50)
> Feature: hide analytics features if not enabled

- app/helpers/check_resolvability_helper.rb
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/692
Use URI.join
```ruby
if response.is_a?(Net::HTTPRedirection) && response['location']
uri = URI.join(uri, response['location'])
```
With URI.join we can handle redirection when response['location'] is relative path or it's absolute path or if it's new URI
- Examples
| Original URI                    | Response Location         | `URI.join` Result                  |
|---------------------------------|---------------------------|------------------------------------|
| `http://example.com/path/`      | `/newpath/something/`          | `http://example.com/newpath/something/` |
| `http://example.com/path/`      | `newpath/something/`           | `http://example.com/path/newpath/something/` |
| `http://example.com/path/`      | …
> Fix: Check resolvability redirection

- app/assets/stylesheets/account.scss
- app/controllers/home_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/views/users/show.html.haml
- config/routes.rb
- test/integration/login_flows_test.rb
- test/system/login_flows_test.rb
- Fix custom ontologies set feature not working
- Fix the issue when we clear the ontologies in the ontologies custom set feature
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/88
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/40528935-e50e-4574-bfb6-a87758954cdb
> Fix: Ontologies custom set not working

- app/controllers/ontologies_controller.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/654
Remove the subject fields from the Project and usage block in the summary page
> Feature: remove subject values from the project and usage block in summary page

- app/assets/stylesheets/bioportal.scss
- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/views/home/cookies.html.haml
- app/views/layouts/_header.html.erb
- app/views/layouts/appliance.html.haml
- config/locales/en.yml
- config/locales/fr.yml
- config/routes.rb
fix https://github.com/lifewatch-eric/ecoportal_web_ui/issues/61, add a cookie banner to accept or deny the usage of cookies, and the decision is saved for the session.
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/fe667c72-03d7-4fc3-910c-bb4cb3e7f2d2
* Add set cookie action (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/e296856460bc0c9fa45d817ccdaf0545051d0bc0)
* Add link button, component helper (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/294b78ffe70e6a578d97a9083421c0ec76cf8078)
* Add coolie modal view (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/91163888cf5eba7ac359b4ad2741291ee63889d1)
> Feature: Add cookie banner

- app/helpers/ontologies_helper.rb
- app/views/ontologies/sections/metadata/_ontology_description_section.html.haml
- test/system/submission_flows_test.rb
Fix https://github.com/agroportal/project-management/issues/532
> Fix: update summary page categories display to show acronym with tooltip

- app/assets/stylesheets/components/search_input.scss
- app/components/agent_search_input_component/agent_search_input_component.html.haml
- app/components/search_input_component.rb
- app/components/search_input_component/search_input_component.html.haml
- app/components/search_input_component/search_input_component_controller.js
- app/controllers/agents_controller.rb
Related issues:
https://github.com/agroportal/project-management/issues/465
https://github.com/agroportal/project-management/issues/571
Related api PR:
https://github.com/ontoportal-lirmm/ontologies_api/pull/86
Changes:
- Make agents search field component results not limited to 4 results.
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/7989bf68-37cd-4885-bfb4-90075e8a26e5
- Make agents searchable by affiliations, identifiers, acronym, email and home page.
- Update the agent search input to display the result in this format `Orga name (ACRONYM) – ROR:003vg9w96` and for persons `Person Name – ORCID:0000-1524-5487-5487`.
> Feature: Enhance agents search input component

- app/assets/stylesheets/agents.scss
- app/controllers/agents_controller.rb
- app/helpers/agent_helper.rb
- app/views/agents/_form.html.haml
- app/views/layouts/_header.html.erb
- app/views/users/_form.html.haml
- test/system/agent_flows_test.rb
Related issue:
https://github.com/agroportal/project-management/issues/545
Demo:
https://github.com/user-attachments/assets/2c8cfe26-f6da-4aad-b3ef-417af816637a
> Feature: Make agent indentifiers field set by default based on agent type

- app/controllers/application_controller.rb
- app/controllers/instances_controller.rb
- app/controllers/ontologies_controller.rb
- app/controllers/properties_controller.rb
- app/helpers/ontologies_helper.rb
- app/helpers/properties_helper.rb
- app/javascript/controllers/history_controller.js
- app/views/layouts/_ontology_viewer.html.haml
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/715
I disabled auto clicking on the first element of the tree (still will be highlighted) and made by default the right section initialized with the details of this first element.
So we get the exact behavior we want (like for the concepts tab)
> Fix: propertyid param auto added to summary page URL

- app/controllers/agents_controller.rb
- config/locales/en.yml
- config/locales/fr.yml
related issue:
https://github.com/agroportal/project-management/issues/577
related back PR:
https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/152
Changes:
- Humanization of the agents form errors (errors handled: nil/empty required values errors, unique identifiers errors).
- Accept all forms of ORCIDs (16 digits, ORCID URL with or without "www." and with or without scheme http/https) then in all cases we pass it in this form to the back: 1234-1234-1234-1234
- Accept all forms of RORs (9 characters, Full URL with 'https://ror.org/' with or without scheme http/https) then in all cases we pass it in this form to the back: 02mn0vt57
- If the orcid is not valid, we pass the value invalid_orcid and the back generates an error
- if the ror is not valid, we pass the value …
> Fix: enhance agents errors messages

- app/controllers/agents_controller.rb
- app/views/agents/_form.html.haml
- test/application_system_test_case.rb
- test/fixtures/agents.yml
Fix the issues 2 and 3 here:
https://github.com/agroportal/project-management/issues/598#event-13766344360
Done in this PR:
- Fix: identifier for organizations is ror and for persons is orcid (I found that reversed in the code)
- Disable multiple identifers for agents in agents form (1 orcid for persons, 1 ror for organizations)
- Fix a lost code from this PR: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/721
> Fix: Disable multiple identifiers for agents

- app/helpers/multi_languages_helper.rb
fix https://github.com/agroportal/project-management/issues/547
The issue appears when ontology does not have language defined in the submission naturalLanguage, e.g localhost:3000/ontologies/BAGO?p=classes, where all language is selected by default, but in reality it is the default portal language (English) that is displayed.
> Fix: set as default language to portal language if naturalLanguage is empty

- app/components/display/search_result_component.rb
- app/components/display/search_result_component/search_result_component.html.haml
- app/controllers/concerns/search_aggregator.rb
- app/controllers/search_controller.rb
- app/helpers/multi_languages_helper.rb
After https://github.com/ontoportal-lirmm/ontologies_api/pull/82, the search API does the language filter in the backend, so no more needs to be done in UI.
-  use multilingual helper to select the right label to show in search page (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/c05b052e1ca832865dfed80cd2c88e58b97add1e)
> Fix: use multilingual helper to select the right label to show in search page

- app/controllers/ontologies_controller.rb
- app/views/properties/_show.html.haml
- config/locales/en.yml
- config/locales/fr.yml
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/708, now we have two new lines for describing the range and domain and range of a Property. In addition, the raw data section is now filled with all the properties related to that property.
> Feature: Add properties range domain the propery show page 

- app/views/layouts/_notices.html.haml
Show License notice only for logged in admin users
> Feature: Show license notice only for logged in admin users

- app/views/annotator/index.html.haml
- config/locales/en.yml
- config/locales/fr.yml
Adding multilingual support in annotator select ontologies
(changed to only modify `select ontologies`)
> Fix: Add multilingual support in annotator select ontologies 

- app/views/home/cookies.html.haml
- app/views/layouts/_footer.html.haml
- config/bioportal_config_env.rb.sample
- config/locales/en.yml
- config/locales/fr.yml
Related [issue #755](https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/755).
Adding language-specific anchors to footer section links and the cookie banner so that it points to the correct language section in the docs.
NB:
- Anchors must be removed from the [config file](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/master/config/bioportal_config_env.rb.sample):
https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/4cdc1aaefb84c1e8609e88e4ec70041e82631abb/config/bioportal_config_env.rb.sample#L288-L292
> Fix : Add language-specific anchors to footer section links and the cookie banner

- Gemfile
- Gemfile.lock
- app/components/language_field_component.rb
- app/helpers/collections_helper.rb
- app/helpers/multi_languages_helper.rb
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/759, by using https://github.com/countries/countries gem(dependency) to detect countries by alpha code (e.g 'br' will be 'Brazilian') 
In addition, now support countries' flags 
- Add countries gem to detect countries languages by alpha code (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/9e2233441b78a58f8eff773e9e1aa128e155bac8)
- Fix collections tab labels sorting when all languages are selected (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/3c78807fb421b710664aeddaba455e8e331f31c2) related to #754
> Feature: Support countries as languages

- app/controllers/admin/categories_controller.rb
- app/controllers/taxonomy_controller.rb
- app/helpers/application_helper.rb
- app/views/admin/categories/_form.html.haml
Require: https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/162
- Update categories selector in the admin page to allow the selection of multiple parent categories (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/772/commits/b55e1b30d45cb335b60d93a6acfe21336b330ce6)
- Handle multiple categories in categories page (display them multiple times under each parent) (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/772/commits/81b2aee856b23c9077a71d45ac7969a233ffb428)
> Feature: Allow multiple parentCategories

- app/helpers/collections_helper.rb
- app/javascript/controllers/turbo_frame_controller.js
Fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/761 by ensuring that the custom fix done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/642 does apply only for the bug in the ontology viewer. 
[Screencast from 2024-10-11 19-49-46.webm](https://github.com/user-attachments/assets/e6f8727d-e6bb-408e-b97b-4606e2735d4c)
> Fix: browse page white page issue 

- app/assets/stylesheets/search.scss
- app/components/display/search_result_component.rb
- app/components/ontology_browse_card_component.rb
- app/components/ontology_browse_card_component/ontology_browse_card_component.html.haml
- app/controllers/concerns/search_aggregator.rb
- app/controllers/concerns/submission_filter.rb
- app/controllers/ontologies_controller.rb
- app/controllers/search_controller.rb
- app/helpers/application_helper.rb
- app/helpers/components_helper.rb
- app/helpers/federation_helper.rb
- app/helpers/instances_helper.rb
- app/helpers/mappings_helper.rb
- app/helpers/urls_helper.rb
- app/views/ontologies/browser/_ontologies.html.haml
- app/views/ontologies/browser/browse.html.haml
- app/views/recommender/index.html.haml
- app/views/search/index.html.haml
- config/locales/en.yml
- config/locales/fr.yml
- Add text for api json button in search page and show it only when the search is performed (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/f3aa7b4cef8cca09f826fc64e4e5801743537d2d)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - -
-----
- Show results count separately for every portal in federated search and browse (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/20d85ec46637f25fc9a233ae3351ba49b35e562d) (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/63f27eea2a129752e24b8e978f400684cef9f968) (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/76c1db5811ebf6e5134045b0b682ad5a903858ad) (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/caf7353897 …
> Feature: Add federation results counts grouped by portal

- app/helpers/components_helper.rb
Source: https://github.com/agroportal/project-management/issues/619
Put back `category chip component` and `group chip component` that are deleted in a code cleaning activity by mistake, and this caused breaking upload ontology page that is still using them.
> Fix: Put back category chip component alias to group chip component

- app/controllers/concerns/search_aggregator.rb
- app/controllers/ontologies_controller.rb
- app/controllers/search_controller.rb
- app/helpers/federation_helper.rb
- app/views/ontologies/browser/browse.html.haml
- app/views/search/index.html.haml
- Change the name of the function `federation_enabled?` used in the search controller, to `federation_portals_enabled?` to use the name `federation_enabled?` to specify if the federation is enabled or disabled from the config file.
- Check if there's in the config file a portal that has an `api` and an `api_key`, if no one is found then we set the federation to disabled.
- If the federation is disabled then we don't display the federation inputs in search and browser pages
> Feature: Add enable/disable federation option

- app/controllers/search_controller.rb
Require: https://github.com/ontoportal-lirmm/ontologies_api_ruby_client/pull/21
Source: https://github.com/agroportal/project-management/issues/619
**PR description**
After adding the federation to the search, the search results are now returned as a hash instead of an object, so to access to the collection key of the results we need to use `[:collection]` instead of `.collection`
> Fix: Jump to infinit loading

- app/helpers/application_helper.rb
- app/views/search/index.html.haml
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/709
> Fix: Include views in ontologies selector of search page

- app/helpers/collections_helper.rb
Related issue: https://github.com/agroportal/project-management/issues/619
**Issue screenshot**
**Issue log**
**Changes**
- Include `MultiLanguagesHelper` in `CollectionsHelper` to make sure that `main_language_label` function that is used in `get_collections` function in `CollectionsHelper` is defined.
**Fix screenshot**
> Fix: ontology collections tree raising an exception

- app/controllers/concepts_controller.rb
This PR provides partial improvements to the tree view performance. However, the primary bottleneck is in the backend, which requires specific endpoints optimized for the tree view, rather than relying on the default concept endpoints. 
- **Optimized data retrieval in `ConceptsController#index`:**
The most time-consuming call when expanding a subtree is `@concept = @ontology.explore.single_class({full: true}, params[:id])`
In this PR, it has been updated to `@concept = @ontology.explore.single_class({display: 'prefLabel'}, params[:id])`, as only the prefLabel and id are necessary at this level.
_(Note: This change provides a slight improvement in response time but does not fully resolve the delay.)_
- **Removed redundant sorting:**
Sorting of concept children was duplicated both in the …
> Fix: Improve concepts tree performance

- app/helpers/application_helper.rb
- app/views/home/index.html.haml
- app/views/ontologies/ontologies_selector/ontologies_selector_results.html.haml
When we disable the slices using `$ENABLE_SLICES=false` in the config files we still see in the home page the slices section. This PR prevents that.
> Fix: Disable slices not hiding the slices section in the home page 

- app/assets/stylesheets/mappings.scss
- app/components/link_text_component.rb
- app/controllers/mappings_controller.rb
- app/helpers/mappings_helper.rb
- app/views/mappings/_concept_mappings.html.haml
- app/views/mappings/_mapping_table.html.haml
- app/views/mappings/_show_line.html.haml
- config/locales/en.yml
- config/locales/fr.yml
Related issue: https://github.com/lifewatch-eric/ecoportal_web_ui/issues/82
- Change mappings table font size and different spacings
- Use a basic text instead of a chip to display concepts
- Use icons for mappings source, home icon for internal, external-link icon for external, "I-P" for Inter-portal with a tooltip displaying the source on hover
- Display the first and the last letter of the type and display the full type in tooltip on hover.
- Hide relations column when it's completely empty.
- Hide actions column if no mapping is of type REST (empty column because we display actions only for the mappings of type REST)
**Screenshot**
> Feature: update concept mappings table UI

- app/assets/stylesheets/browse.scss
- app/assets/stylesheets/components/switch.scss
- app/controllers/concerns/submission_filter.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/827
- Fix broken switch style when using a long text beside it (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/39a93873f41fcc8150a8ed0531bf45c79ef816cf)
- Don't display current portal button in browse page results (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/c8ad07ae28fed1d76cf44c681f6a82838d3d4a22)
**Before**
**After**
> Fix: Browse page switch style, and don't display current portal name button in browse results

- app/controllers/concerns/search_aggregator.rb
Fixed issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/829
The previous logic to detect duplicate search results combined the concept URI and ontology acronym. However, it attempted to retrieve the ontology acronym using `element[:root][:ontology_acronym]`, which doesn’t exist as a key under `element[:root]`. Instead, only the ontology ID is available in this structure.
To resolve this:
- Extracted the ontology acronym from the available ontology ID.
- Replaced the previous key lookup with this derived acronym to ensure proper duplicate detection.
> Fix: Search federation duplicated results merging issue

- app/helpers/application_helper.rb
- app/helpers/ontologies_helper.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/819
**Source of issue**
To get the subscriptions of a user we used to the the call with the param `?include=subscription` which used to display the users with their subscription list that includes ontologies acronyms, but after idk what we did in the back side the same call gives us a result like this one
**The solution is** to do `include=all` and this is the result of it
https://github.com/user-attachments/assets/618f2f88-4a06-4e1a-b40d-932540b5ecc1
> Fix: Watch button count and state

- app/controllers/agents_controller.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/799
- Add `*` to the agents search query (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/688466f37eb82f3082dbf3424481d9d29b92baed)
> Fix: Agent search not working well 

- app/controllers/collections_controller.rb
- app/helpers/application_helper.rb
- app/helpers/components_helper.rb
- app/helpers/ontologies_helper.rb
- app/views/concepts/_list.html.haml
- app/views/notes/_new_comment.html.haml
- app/views/notes/_new_proposal.html.haml
Fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/817, https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/813, https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/818 and https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/796
- Enforce add comment and proposal buttons to use turbo top frame (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/8a4b78f8050e1193aa966b912c59841bcb5f80c1) to resolve https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/817
- Fix property content missing message (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/846/commits/ce948aaceff4f179182787e37e082f797129518e) to resolve https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/796
- Make the notes form use the correct button components …
> Fix: Notes buttons showing, some properties details, and no collection selection  showing content missing or an error alert

- app/helpers/submission_inputs_helper.rb
- app/views/ontologies/_submission_location_form.html.haml
- app/views/ontologies/new.html.haml
https://github.com/user-attachments/assets/ecd16b17-9266-4c2a-82fb-24470c5da9aa
> Fix: Add a star for the required fields in the upload form

- app/assets/stylesheets/taxonomy.scss
- app/components/display/taxonomy_card_component.rb
- app/components/display/taxonomy_card_component/taxonomy_card_component.html.haml
- app/views/taxonomy/index.html.haml
- config/locales/en.yml
- config/locales/fr.yml
Fix: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/788
- Detect if the taxonomy description is a link and handle that (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/b961561ddc8d528c28f2d9eff7dbcc8d1bebd289)
If it's not a link we keep the default behavior
- Make portal name dynamic in taxonomy page description (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/7c432791635c61154fa826d42d32974fcb623483)
- Retouch taxonomy page description to replace "In 2024, we moved to UNESCO nomenclature for fields of science and technology" by "In 2024, we moved to UNESCO Thesaurus (https://vocabularies.unesco.org/)." (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/2606cbe04a246218d6b35d1f0a56783a2791874f)
> Fix: Improve taxonomy page, fix static portal name, detect description link

- app/assets/stylesheets/components/tree_view.scss
**Fix:** https://github.com/agroportal/project-management/issues/632
- Prevent word break for the tree view elements (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/d366f2c8a44dfb37162a2a11ca56c359f807da8e)
> Fix: `Tree View` Prevent word break for the  elements

- app/components/federated_portal_button_component.rb
- app/components/federated_portal_button_component/federated_portal_button_component.html.haml
- app/helpers/federation_helper.rb
Fix: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/853
Changes:
- Fix `federated portal button` link of the current portal in browse page(https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/527902381749d5a0e47471bd42b17a8fbeec9e0b)
- Make it open in the current tab (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/31a42dacb3cbdd1f3c366e2bde5121c59b25788e)
> Fix: Federation portal button link

- app/assets/stylesheets/taxonomy.scss
- app/controllers/taxonomy_controller.rb
- app/helpers/components_helper.rb
- app/views/taxonomy/_taxonomies.html.haml
- app/views/taxonomy/index.html.haml
- config/locales/en.yml
- config/locales/fr.yml
- Add null safety for parent categories list.
- Add empty illustration for categories/groups. And display a button to create groups/categories if the user is an admin.
**Non admin users**
**Admins**
> Fix: Taxonomy empty list

- app/helpers/federation_helper.rb
- The bug was introduced by a function that converts API links into UI links. This function added `/`each time it does. So we got double slashes in the link (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/2c1d38b2afb3c6a3103d08bd254d72eb70400a8a)
- Ensure trailing slash in federation portals ui and api links (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/873/commits/07f3c1570716084cb0c1474c9b8f154218441372)
> Fix: Browse page links multi slashes

- app/controllers/application_controller.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/863
Changes: 
- Fix a wrong condition done in this PR: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/748
So now the default behavior will work, while keeping the preventing of selecting a disabled language like German for example.
Screenshots:
> Fix: Change portal language

- app/helpers/federation_helper.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/859
- Include counting duplicated results for each portal (not only the canonical) in both federated browse and search
(https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/870/commits/9f0fee89da72ef8a9b0304a483039d10a62e6197) (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/870/commits/5f460ffc76249688fb4b0397e2997dc31cc2d2ec)
**Federated browse**
**Federated search**
> Fix: `Federated search/browse` results count by portal

- app/controllers/home_controller.rb
- app/views/home/portal_config.html.haml
Fix: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/835
Before:
After:
> Fix: Prevent display home portal tooltip if we get a non complete response

- app/controllers/ontologies_controller.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/862
- On the federated browse page, only root categories (categories without parents) from other federation portals are displayed (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/877/commits/82cc2cc8bd33dc94470f9cbba32d42d7f091936f)
> Feature: Keep only top level categories in federated browse page

- app/controllers/admin/categories_controller.rb
- app/helpers/application_helper.rb
- app/views/admin/categories/_category.html.haml
- config/locales/en.yml
- config/locales/fr.yml
- Prevent delete category if still used as parent category (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/357a86ecd3db857baacf89f18a22a585bf19de20)
> Fix: Prevent delete category if still used as parent category

- app/controllers/users_controller.rb
- app/views/ontologies/browser/browse.html.haml
- app/views/users/show.html.haml
- config/locales/en.yml
- config/locales/fr.yml
When user has access to private ontology (i.e he is in the list of acl attribute of the ontology) , he cannot see it in the browse page because he does not have the option so filter by private ontologies, and also he can not see it in the account page or something.
- Users that has access to private ontologies (not admin of the ontology) can see these ontologies from the interface through account settings (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/b5c897a941f748723b0c242371e9c09f154a1dfd)
- Make show private ontologies switch displayed for all logged in users and not only for admins
> Feature: Show private accessible ontologies in account and browse page

- app/helpers/application_helper.rb
- app/helpers/submission_inputs_helper.rb
- app/javascript/controllers/parent_categories_selector_controller.js
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/904
**Browe page**
- Selecting a category will auto select all its children
- Deselecting a category will auto deselect all its children
**Edit/Upload forms**
- Selecting a category will auto select its parents
- Deselecting a category will auto deselect its children
- In these examples I used TECH and FARMING categories, TECH is the parent category of FARMING
**Browse**
https://github.com/user-attachments/assets/29d1b944-e08f-49be-b10c-5f2a4e13fb44
**Upload/Edit forms**
https://github.com/user-attachments/assets/500cb9fa-8f4e-4fbb-85a4-bad3df5fc8ea
> Fix: Wrong logic in categories association with parents for upload/edit forms

- app/helpers/federation_helper.rb
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/909
When attempting to retrieve the canonical portal for a duplicated ontology during a federated call, the current implementation counts references across all portals, instead of limiting the count to only those mentioned in the current request. 
The issue raised in this example (https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/909) is that AgroPortal and EcoPortal were selected, but the results included an ontology with the canonical portal BiodivPortal.
This PR updates the logic to count the most-referenced portals for duplicated ontologies using only the list of portals mentioned in the current request.
> Fix: Canonical portal choice only from the request portals list

- app/javascript/controllers/turbo_frame_controller.js
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/901
- Checking the federation input chip on the browse page automatically triggers the sorting filter to sort by name. This causes the page to reload multiple times, which leads to the turbo frame’s loading animation disappearing.
- Performing category-parent association logic also causes the same issue, as multiple category chips are selected in quick succession.
- Rapidly selecting parameters on the browse page can also result in the issue, causing a white page to appear on the right without any animation.
- Ensure that each time we update a turbo frame, the busy attribute is set to true to show the animation.
- This logic is executed at the end of the JavaScript call stack using requestAnimationFrame method, …
> Fix: Missing loading animation when loading multiple turbo frames in a fast way

- app/components/concept_details_component.rb
- app/components/list_items_show_more_component.rb
- app/components/list_items_show_more_component/list_items_show_more_component.html.haml
- app/helpers/components_helper.rb
- app/helpers/multi_languages_helper.rb
- app/helpers/ontologies_helper.rb
- app/views/concepts/_details.html.haml
* https://github.com/ontoportal/ontoportal_web_ui/pull/28
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/445 and https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/894 
See example with https://stageportal.lirmm.fr/ontologies/AGROVOC?p=classes
[Screencast From 2025-01-10 11-30-13.webm](https://github.com/user-attachments/assets/e8d185fa-f736-4fb7-84b1-31fccc33418f)
* Add list items component to hide container items if more than max items (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/51b0afab1f71a94434a03cca286a261cb4dcb14b)
* Use list item component in concept details component for synonyms and others  (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/db67ff3faac9c7df781bac6104c5351ce34ef99d)
> Feature: Add see more items component

- app/assets/stylesheets/application.css.scss.erb
- app/helpers/ontologies_helper.rb
- app/views/layouts/_ontology_viewer.html.haml
One a user go to the ontology viewer of an ontology, e.g https://stageportal.lirmm.fr/ontologies/AGROVOC, it loads the current visited page and in the background fetch th remaining sections. 
It is good if our API could support that amount  of calls,  but unfortunately it does overload the server with calls that are even possibly not even seen by the end users (e.g  mappings section)  
Now the following section are loaded in the background `summary, classes, properties,instances,collections,schemes`
And the following will be loaded only in visit `mappings, notes, widgets, sparql`
* Make the ontology viewer load the sections only if visited (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/6ab8354e3fc49152b7b72d621670ba9f8a9b3927)
* Update the ontology viewer to lazy the section …
> Feature: disable eager loading in production and  load the sections only if visited

- app/helpers/multi_languages_helper.rb
404 error on StagePortal when trying to do a search on search page.
- Update `display_in_multiple_languages` method to add some missing params to it (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/c4e4b1d7045991a551f6106326ba249e4564f2b3)
The method was defined with only one param which is label, but expecting two other params which are style_as_badge and show_max.
> Fix: `display_in_multiple_languages` method to add the missing params

- app/helpers/home_helper.rb
https://github.com/user-attachments/assets/9a6ec531-70aa-4869-8844-a6f69f87ba73
In the `portal_config_tooltip` method, there is a parameter named `portal_name`. However, within the same context, there is also a method named `portal_name`, causing a conflict when working inside `portal_config_tooltip`.  
- Renamed the `portal_name` parameter to `portal` in the `portal_config_tooltip` method. 
https://github.com/user-attachments/assets/ef04c366-9f18-4109-956c-2a1a093af5ab
> Fix: Home page portals tooltips

- .env.sample
- app/controllers/application_controller.rb
- app/controllers/ontologies_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/application_helper.rb
- app/helpers/ontologies_helper.rb
- config/bioportal_config_env.rb.sample
Related Issue : http://github.com/ontoportal-lirmm/bioportal_web_ui/issues/933
1. Disable **ontology upload** button for non-privileged users in read-only mode. This change ensures that non-privileged users cannot see or interact with the ontology upload button when the portal is in read-only mode. The button is now only visible to admins in this state.
2. When the portal is in read-only mode. The page `/ontologies/new` is now restricted to admins only in this state, preventing unauthorized users from creating new ontologies while the portal is read-only.
https://github.com/user-attachments/assets/53deebe9-e215-4e9b-aaae-e7788bad127d
> Feature: Restrict access to ontology creation for non-privileged users in read-only mode

- app/helpers/multi_languages_helper.rb
- app/helpers/ontologies_helper.rb
- config/locales/en.yml
- config/locales/fr.yml
1. Update the french translation based on the [curated CSV](https://docs.google.com/spreadsheets/d/1Vs1tXnSfDQVk9p1fF0U7dAt7AVwSVx5uOOrEvvlYL9Y/edit?gid=0#gid=0) File.
2. Remove the `Beta` tag from the french language
-  **Before:**
- **After:**
> Fix: French support finalization

- .github/workflows/deploy.yml
While reviewing the deployment workflow, I noticed that deployment on push is enabled, but it is currently not working. After checking the logs, I found the following error preventing the deployment:
- Disabled the automatic deployment on push, and kept the manual deployment option via the "Actions" tab on GitHub which is our desired behavior.
- Clean code.
> Fix: auto deploy on push issue

- app/controllers/home_controller.rb
- app/helpers/federation_helper.rb
- app/helpers/home_helper.rb
- app/views/home/portal_config.html.haml
After implementing MOD-API, the pop up of ontoportal instances is not working and that's because we changed the structure of the / route. 
Why:
- Before we were expecting to have the data as a hash (and the  federated_portals as hash also)
- Now with MOD-API we are expecting an object of type `LinkedData::Client::Models::SemanticArtefactCatalog` and the federated_portals as an array 
This fix will handle both case, so that the portals that didn't implement the MOD-API will not be broken
> Fix: ontoportal instances popups after migrating to MOD-API

- app/controllers/concerns/submission_updater.rb
- app/helpers/ontologies_helper.rb
related issue:
- https://github.com/agroportal/project-management/issues/744#issuecomment-3264937443
subject not shown correctly because the URIs of the subject has some white spaces. 
The root problem was that when we edit the ontology metadata sometimes the users add spaces or even add a white space elements without any character.
here we strip the values before saving the metadata.
> Fix: strip values when editing ontology metadata

- app/helpers/metrics_helper.rb
- app/views/home/_metrics.html.haml
- config/locales/en.yml
- config/locales/fr.yml
See:
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/1152
> Feat: Add agents number to the home page metrics section
